image:
  tag: "v2.0.0-rc6"
service:
  type: NodePort
  port: 5050
  nodePort: 30377
ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  className: "nginx"
  pathtype: ImplementationSpecific
  hosts:
    - host: zot-ai.palette-adv.spectrocloud.com
      paths:
        - path: /
  tls: 
    - hosts:
      - zot-ai.palette-adv.spectrocloud.com
      secretName: zot-tls
httpGet:
  scheme: HTTP
mountConfig: true
configFiles:
  config.json: |-
    {
      "http": {
        "address":"0.0.0.0",
        "port":"5050",
        "auth":{
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        }
      },
      "log": {
        "level":"debug"
      },
      "extensions": {
        "search": {
          "enable": true
        },
        "ui": {
          "enable": true
        },
        "mgmt": {
          "enable": true
        }
      },
      "storage": {
        "dedupe": true,
        "rootDirectory": "/tmp/zot",
        "gc": true,
        "gcDelay": "2h"
      }
    }
mountSecret: true
secretFiles:
  htpasswd: |-
    admin:$2y$05$vmiurPmJvHylk78HHFWuruFFVePlit9rZWGA/FbZfTEmNRneGJtha
    user:$2y$05$L86zqQDfH5y445dcMlwu6uHv.oXFgT6AiJCwpv3ehr7idc0rI3S2G
authHeader: "YWRtaW46YWRtaW4="
